### ISSUE TITLE
Hi,Why QPSK modulation's LLR is that?

### ISSUE THREAD

**Issue by cod1239** [robmaunder/polar-3gpp-matlab#1]
I am a rookie in new radio.
In plot_BLER_vs_SNR.m ,I find the LLR vector be caculated by your method(In line 151-154).
But I find some paper,the LLR in QPSK modulation,use 'ln' to caculate,and you donot use it.
can you tell me why? thank you!

**Comment by robmaunder** [comment]
Hi cod1239,

LLRs are defined as LLR = ln(P(bit=0)/P(bit=1)) - I think this is the ln that you are referring to. To get P(bit = 0) and P(bit = 1) in QPSK, you need to use exp - this comes from the Gaussian noise equation. So rather than using exp to get P(bit = 0) and P(bit = 1), then use ln to get LLR, we can cancel the exp and the ln out. This is why we don't need ln (or exp) to get LLRs from QPSK.

Take care, Rob.

**Comment by kumuds4** [comment]
How about the approximate LLR's for 64-QAM or say 8-PAM? I have all individual LLR's. My question is how to add them to get the total of LLR's to go for decoding. Here 8-PAM is not same as 4-PAM. QPSK, I have seen your codes. I am talking about polar codes, higher order modulation. I know eEidl's work and Tavildar's as well. I would like to keep the polarization base as 2x2 instead using Mahadafir's approach. Thank you so much. Matlab or Python either OK.

**Comment by robmaunder** [comment]
Hi kumuds4,

I use QPSK here because that is what 3GPP used throughout the polar code design and analysis process. Also, polar-coded control information is mostly (but not always) transmitted using QPSK in 5G New Radio. 

But the code I have provided here can be readily combined with a higher order modulation scheme - the LLRs produced by a higher-order demodulator can be used directly with this polar decoder.

Take care, Rob.

**Comment by kumuds4** [comment]
Hi Professor Maunder,

Thank you so much. Yes, the LLR's are fine. I have figured out to calculate
piece-wise approximations of  LLR'S for 8-ASK,  64-QAM. However, I am still
unable to add approximate LLR's i.e. let us say using, 8-ASK for three
bits, b_{0}, b_{1} and b_{3}, [y_{i}= Z]; [ y_{i}=[abs(Z-4)];
[y_{i}=abs((Z-4 )+2)].  These are three and Euclidean distance keeps
changing. That's where it becomes different from BPSK, QPSK.

Once, I get all these added to feed to decoder, I can do BER, and BLER both
for QAM as well. When, minute, please suggest, any good method to add the
approximate LLR's obtained.

Best regards,

Kumud S. Altmayer

**Comment by robmaunder** [comment]
Hello again,

You can see Matlab code for soft decision demodulation at...
https://github.com/robmaunder/exit-matlab

You just need to modify the bit_labels and constellation_points in soft_demodulate.m

Take care, Rob.
