### ISSUE TITLE
Cannot run plot_SNR_vs_A.m

### ISSUE THREAD

**Issue by cod1239** [robmaunder/polar-3gpp-matlab#2]
Thank your work!
When I run plot_SNR_vs_A.m,a error occur.
Error in the line 60 ,info_bit_pattern =get_3GPP_info_bit_pattern(K,N,E),it says I should be no greater than N(line 57)
And in function get_3GPP_info_bit_pattern, I is the input parameter K,and N is generated by N = length(Q_N)(line49) ,Q_N is input parameter N. And N is generated by N = get_3GPP_N(K,E,n_max)(In line58, plot_SNR_vs_A.m). So N is a integer number,and after length(),N is always equal 1. I think it is reason.
In PDCCH_encoder.m or other procedure, Q_N is generated by get_3GPP_sequence_pattern(N), it is a vector , so can be use in get_3GPP_info_bit_pattern(K,N,E). And parameter 'mode', it is also not used in plot_SNR_vs_A.m.
Maybe it is a small mistake, or a something right but I have not understand.

**Comment by robmaunder** [comment]
This was happening because plot_SNR_vs_A was trying to simulate a combination of information block length A and encoded block length E that is not supported. I had forgotten about plot_SNR_vs_A for a while, but I have just updated it to work better with the rest of the code. In particular, it now skips any combinations of A and E that are not supported.

Take care, Rob.
